In [1]:
#Importing necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [16]:
#loading the dataset and reading the head
raw_data =pd.read_csv('survey.csv')
raw_data.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [26]:
#Data Cleaning 
data=raw_data[raw_data['Gender']==('M')].index
raw_data.drop(data, inplace=True)
raw_data1=raw_data.drop(['comments'], axis=1)
raw_data1.head(100)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
2,2014-08-27 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,2014-08-27 11:31,33,Male,United States,TN,NaN,Yes,No,Sometimes,25-Jun,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,2014-08-27 12:23,35,Male,United States,MO,No,Yes,No,Rarely,25-Jun,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,No,Don't know,No
107,2014-08-27 12:25,28,Male,Brazil,NaN,No,Yes,Yes,Rarely,25-Jun,...,No,Don't know,Maybe,No,Yes,Yes,No,No,Don't know,Yes
108,2014-08-27 12:28,34,m,United States,TN,No,Yes,No,Never,25-Jun,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
109,2014-08-27 12:28,32,Male,United States,WA,No,No,Yes,Sometimes,26-100,...,Yes,Somewhat difficult,Maybe,No,Some of them,Yes,No,Maybe,Yes,No
110,2014-08-27 12:29,22,Male,United States,NY,No,No,Yes,Sometimes,500-1000,...,Yes,Don't know,Yes,No,No,No,No,Yes,No,No

In [28]:
treatment_yes=raw_data1[raw_data1['treatment'].str.contains("Yes")]
treatment_yes.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
3,2014-08-27 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
6,2014-08-27 11:31,35,Female,United States,MI,NaN,Yes,Yes,Sometimes,05-Jan,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No
8,2014-08-27 11:32,42,Female,United States,IL,NaN,Yes,Yes,Sometimes,100-500,...,No,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No
10,2014-08-27 11:32,31,Male,United States,OH,NaN,No,Yes,Sometimes,25-Jun,...,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No